cc_test(
    name = "allocTest",
    srcs = glob(["all_test.cpp"]),
    copts = ["-std=c++17"],
    deps = ["//:CorekvLib",
           "@googletest//:gtest_main"],
)

cc_test(
    name = "skiplistTest",
    srcs = glob(["skiplist_test.cpp"]),
    copts = ["-std=c++17"],
    deps = ["//:CorekvLib",
           "@googletest//:gtest_main"],
)


cc_test(
    name = "bloomFilterTest",
    srcs = glob(["bloomfilter_test.cpp"]),
    copts = ["-std=c++17"],
    deps = ["//:CorekvLib",
           "@googletest//:gtest_main"],
)


cc_test(
    name = "cacheTest",
    srcs = glob(["cache_test.cpp"]),
    copts = ["-std=c++17"],
    deps = ["//:CorekvLib",
           "@googletest//:gtest_main"],
)

cc_test(
    name = "footerTest",
    srcs = glob(["footer_test.cpp"]),
    copts = ["-std=c++17"],
    deps = ["//:CorekvLib",
           "@googletest//:gtest_main"],
)


cc_test(
    name = "tableBuilderTest",
    srcs = glob(["table_builder_test.cpp"]),
    copts = ["-std=c++17"],
    deps = ["//:CorekvLib",
           "@googletest//:gtest_main"],
)
cc_test(
    name = "blockIterTest",
    srcs = glob(["block_iter_test.cpp"]),
    copts = ["-std=c++17"],
    deps = ["//:CorekvLib",
           "@googletest//:gtest_main"],
)

cc_test(
    name = "manifestTest",
    srcs = glob(["manifest_test.cpp"]),
    copts = ["-std=c++17"],
    deps = ["//:CorekvLib",
           "@googletest//:gtest_main"],
)