
cc_library(
    name = "ManifestLib",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob(["**/*.h"]),
    copts = ["-std=c++17"],
    deps = ["//file:FileLib",
            "//logger:LogLib",
            "//utils:UtilsLib"],
    visibility = ["//visibility:public"],
)