
cc_library(
    name = "DbLib",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob(["**/*.h"]),
    copts = ["-std=c++17"],
    deps = ["//logger:LogLib",
            "//utils:UtilsLib"],
    visibility = ["//visibility:public"],
)